version: "2"

networks:
  redis-network:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 10.10.10.0/24
    #       gateway: 10.10.10.254    

volumes:
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local

services:
  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3'
      # - 'REDIS_NODES=10.10.10.1 10.10.10.2 10.10.10.3'
      # - 'REDIS_CLUSTER_ANNOUNCE_IP=10.10.10.1'
      # - 'REDIS_CLUSTER_CREATOR=no'
    networks:
      - redis-network
        # ipv4_address: 10.10.10.1

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3'
      # - 'REDIS_NODES=10.10.10.1 10.10.10.2 10.10.10.3'
      # - 'REDIS_CLUSTER_ANNOUNCE_IP=10.10.10.2'
      # - 'REDIS_CLUSTER_CREATOR=no'
    networks:
      - redis-network
        # ipv4_address: 10.10.10.2

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    depends_on:
      - redis-node-1
      - redis-node-2
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDISCLI_AUTH=redis'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3'
      # - 'REDIS_NODES=10.10.10.1 10.10.10.2 10.10.10.3'
      - 'REDIS_CLUSTER_CREATOR=yes'
      # - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      # - 'REDIS_CLUSTER_ANNOUNCE_IP=10.10.10.3'
      # - 'REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP=10'
      # - 'REDIS_DNS_RETRIES=5'
    networks:
      - redis-network
        # ipv4_address: 10.10.10.3
    ports:
      - '6379:6379'

