# Provider 
terraform {
  required_providers {
    yandex = {
      source = "yandex-cloud/yandex"
    }
  }
  backend "local" {
    path = "terraform.tfstate"
  }
}

provider "yandex" {
  cloud_id                 = var.yandex_cloud_id
  folder_id                = var.yandex_folder_id
  zone                     = var.zone
}


# Nodes
resource "yandex_compute_instance" "microk8s" {
  name        = "microk8s"
  zone        = var.zone
  hostname    = "microk8s.nikmokrov.cloud"
  description = "microk8s"
  platform_id = "standard-v2"

  allow_stopping_for_update = true

  resources {
    cores         = 2
    core_fraction = 50
    memory        = 4
  }

  boot_disk {
    initialize_params {
      image_id = var.image_id
      name     = "root-microk8s"
      type     = "network-ssd"
      size     = "32"
    }
  }

  network_interface {
    subnet_id = "e2loqdquk6b6btrpu62j" #default-ru-central1-b
    nat       = true
  }

  metadata = {
    ssh-keys = "${var.ssh_user}:${file("~/.ssh/yc_ubuntu.pub")}"
  }

  scheduling_policy {
    preemptible = true
  }

}

# Inventory file
resource "local_file" "inventory" {
  content = <<-DOC
    # Generated by Terraform.

    [microk8s]
    ${yandex_compute_instance.microk8s.hostname} ansible_host=${yandex_compute_instance.microk8s.network_interface.0.nat_ip_address}
    [microk8s:vars]
    ansible_user=${var.ssh_user}
    ansible_ssh_private_key_file="~/.ssh/yc_ubuntu"

    DOC
  filename = "../playbook/inventory/prod.ini"

  depends_on = [
    yandex_compute_instance.microk8s,
  ]
}

# Output
output "external_ip_address_microk8s" {
  value = yandex_compute_instance.microk8s.network_interface.0.nat_ip_address
}

# Variables
variable "yandex_cloud_id" {
  default = "b1gcn03m319mu8kiic9q"
}

variable "yandex_folder_id" {
  default = "b1ga7t052sv70padtm26"
}

variable "zone" {
  default = "ru-central1-b"
}

variable "image_id" {
  type = string
  # default = "fd8jvcoeij6u9se84dt5" # centos-7-base
  # default = "fd89dg1rq7uqslc6eigm" # debian-11
  default = "fd8ps4vdhf5hhuj8obp2" # ubuntu-2204-lts
}

variable "ssh_user" {
  # default = "centos"
  # default = "debian"
  default = "ubuntu"
}
