---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  ports:
  - name: outside-nginx-port
    port: 80
    protocol: TCP
    nodePort: 30001
  selector:
    app: nginx-multitool
  type: NodePort
