---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  ports:
  - name: outside-nginx-port
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  selector:
    app: nginx-multitool
  type: LoadBalancer
  # clusterIP: 10.96.128.1
