apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops22
  namespace: devops22
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops22
  namespace: devops22
subjects:
- kind: User
  name: devops22
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devops22
  apiGroup: rbac.authorization.k8s.io