apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-and-multitool-deployment
  labels:
    app: nginx-multitool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
      - name: multitool
        image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        env:
          - name: HTTP_PORT
            value: "8888"

---
apiVersion: v1
kind: Service
metadata:
  name: multitool-svc
spec:
  ports:
  - name: nginx-port
    port: 80
    protocol: TCP
    targetPort: 80
  - name: multitool-port
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: nginx-multitool

---
apiVersion: v1
kind: Pod
metadata:
  name: another-one-multitool
spec:
  containers:
  - image: wbitt/network-multitool
    imagePullPolicy: IfNotPresent
    name: another-one-multitool