apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-volume-deployment
  labels:
    app: shared-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-volume
  template:
    metadata:
      labels:
        app: shared-volume
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo $(date +"%F %T") to stamp.txt >> /output/stamp.txt; sleep 5; done']
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: shared-vol
          mountPath: /output
      - name: multitool
        image: wbitt/network-multitool
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: shared-vol
          mountPath: /input
      volumes:
      - name: shared-vol
        emptyDir: {}

