version: '3.3'

volumes:
    pg_data:

services:
  postgres:
    container_name: postgres
    image: "postgres:13"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./test_dump:/data/backup
    restart: unless-stopped