version: '3.3'

networks:
  pg-network:
    driver: bridge

volumes:
    pg_data-1:
    pg_bkp:
    #pgadmin:

services:
  postgres-1:
    container_name: postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - pg_data-1:/data/postgres
      - pg_bkp:/data/backup
    networks:
      - pg-network
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin4:
    container_name: pgadmin4
    image: "dpage/pgadmin4:6.16"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.loc
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_DISABLE_POSTFIX: "1"
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - pg-network
    ports:
      - 4080:80
    depends_on:
      - postgres
