apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-svc" .Release.Name .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ printf "%s-%s-app" .Release.Name .Chart.Name }}
