{
 "title": "My dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\", mode=\"idle\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "stat",
   "description": "CPU load average 1/5/15",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\"}",
     "legendFormat": "node_load1"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\"}",
     "legendFormat": "node_load5"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\"}",
     "legendFormat": "node_load15"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"}"
    }
   ]
  },
  {
   "title": "File System Size",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"nodeexporter:9100\",mountpoint=\"/\"}",
     "legendFormat": "/"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"nodeexporter:9100\",mountpoint=\"/home\"}",
     "legendFormat": "/home"
    }
   ]
  }
 ]
}