---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Restart clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  pre_tasks:
    - name: Install some useful packages
      become: true
      ansible.builtin.yum:
        name: "{{ useful_packages }}"
        state: present
  tasks:
    - name: Add clickhouse repo
      become: true
      ansible.builtin.yum_repository:
        name: clickhouse
        description: Clickhouse repo
        baseurl: https://packages.clickhouse.com/rpm/stable/
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name: "{{ item }}-{{ clickhouse_version }}"
        state: present
        disable_gpg_check: true
      with_items: "{{ clickhouse_packages }}"
    - name: Generate clickhouse server config
      become: true
      ansible.builtin.template:
        src: "./templates/clickhouse/server-config.j2"
        dest: "/etc/clickhouse-server/config.d/config_override.yaml"
        owner: clickhouse
        group: clickhouse
        mode: '0400'
      notify: Restart clickhouse service
    - name: Generate clickhouse user config
      become: true
      ansible.builtin.template:
        src: "./templates/clickhouse/user-config.j2"
        dest: "/etc/clickhouse-server/users.d/users_override.yaml"
        owner: clickhouse
        group: clickhouse
        mode: '0400'
      notify: Restart clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client --password {{ clickhouse_default_pwd }} -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0


- name: Install Vector
  hosts: vector
  handlers:
    - name: Restart vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  pre_tasks:
    - name: Install some useful packages
      become: true
      ansible.builtin.yum:
        name: "{{ useful_packages }}"
        state: present
  tasks:
    - name: Add vector repo
      become: true
      ansible.builtin.yum_repository:
        name: vector
        description: Vector repo
        baseurl: "https://repositories.timber.io/public/vector/rpm/any-distro/any-version/{{ ansible_architecture }}"
    - name: Install vector package
      become: true
      ansible.builtin.yum:
        name: "vector-{{ vector_version }}"
        state: present
        disable_gpg_check: true
    - name: Delete all other possible vector config files
      become: true
      ansible.builtin.file:
        path: "/etc/vector/{{ item }}"
        state: absent
      with_items: "{{ vector_unneeded_config_files }}"
    - name: Generate vector config file
      become: true
      ansible.builtin.template:
        src: "./templates/vector/vector.j2"
        dest: "/etc/vector/vector.toml"
        owner: root
        group: root
        mode: '0644'
      notify: Restart vector service


- name: Install Lighthouse
  hosts: lighthouse
  handlers:
    - name: Restart nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  pre_tasks:
    - name: Install some useful packages
      become: true
      ansible.builtin.yum:
        name: "{{ useful_packages }}"
        state: present
    - name: Add EPEL repository
      become: true
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  tasks:
    - name: Install nginx
      become: true
      ansible.builtin.yum:
        name: "nginx"
        state: present
        disable_gpg_check: true
    - name: Create lighthouse data dir
      become: true
      ansible.builtin.file:
        path: "{{ lighthouse_path }}"
        owner: nginx
        mode: '700'
        state: directory
    - name: Get lighthouse sources
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        dest: "{{ lighthouse_path }}"
        clone: true
        update: false
    - name: Generate nginx config for lighthouse
      become: true
      ansible.builtin.template:
        src: "./templates/lighthouse/nginx.j2"
        dest: "/etc/nginx/nginx.conf"
        owner: root
        group: root
        mode: '0644'
      notify: Restart nginx service
