apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: github-actions-secret
  namespace: clock-app
  annotations:
    kubernetes.io/service-account.name: github-actions
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: clock-app
secrets:
  - name: github-actions-secret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: continuous-deployment
  namespace: clock-app
rules:
  - apiGroups:
      - ''
      - apps
      - networking.k8s.io
    resources:
      - namespaces
      - deployments
      - replicasets
      - ingresses
      - services
      - secrets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: continuous-deployment
  namespace: clock-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: continuous-deployment
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: clock-app
